Criar componente para o Copyright dos projetos
xproglabs/prensa-designsystem pull request #215
Opened 2021-09-29 15:54 UTC by martinezpoa

2021-09-30 02:02 UTC, gbombassaro requested changes

2021-09-30 02:02 UTC, gbombassaro commented on src/components/Copyright/styled.js
> +export const ContainerFooter = ({ children }) =>
Esse aqui tbm não notei uso

2021-09-30 02:02 UTC, gbombassaro commented on src/components/Copyright/styled.js
> +export const ContainerRight = ({ children }) =>
Esse aqui tbm não notei uso

2021-09-30 02:02 UTC, gbombassaro commented on src/components/Copyright/styled.js
> +export const ContentFooter = ({ children }) =>
Esse aqui tbm não notei uso

2021-09-30 02:02 UTC, gbombassaro commented on src/components/Copyright/consts.js
> +export {
Acho que vale dar uma revisada nesse arquivo pós remoções de conteúdo não utilizado. Creio que tem bastante coisa aqui tbm que não está sendo usada

2021-10-04 12:42 UTC, gbombassaro commented on src/components/Copyright/consts.js
> -  bgColor: 'neutral9',
Acho que podemos manter esse valor, ele já vai atuar como defaultProps ao invés de termos que definir o Component.defaultProps

2021-10-04 12:42 UTC, gbombassaro commented on src/components/Copyright/styled.js
> +ContainerCopyright.defaultProps = {
Mantendo o valor da thread anterior, podemos remover isso aqui

2021-10-04 12:46 UTC, gbombassaro commented on src/components/Copyright/styled.js
> +export const ContainerCopyright = ({  bgColor, children }) =>
```suggestion
export const ContainerCopyright = ({ bgColor, children }) =>
```

2021-10-04 12:46 UTC, gbombassaro commented on src/components/Copyright/types.ts
> +   * @description Defini a cor do texto
```suggestion
   * @description Define a cor do texto
```

2021-10-04 12:46 UTC, gbombassaro commented on src/components/Copyright/types.ts
> +   * @description Defini o texto a ser renderizado
```suggestion
   * @description Define o texto a ser renderizado
```

2021-10-04 12:50 UTC, gbombassaro commented on src/components/Copyright/Copyright.stories.mdx
> +import {Meta} from '@storybook/addon-docs/blocks';
@martinezpoa como ficou essa thread?

2021-10-04 12:51 UTC, gbombassaro commented on src/components/Copyright/styled.js
> +export const ContainerText = ({ children }) =>
@martinezpoa acho que faltou essa thread

2021-10-04 12:52 UTC, gbombassaro commented on src/components/Copyright/consts.js
> +const CONTAINER_TEXT = {
Aqui também não está sendo usado

2021-10-04 18:28 UTC, martinezpoa commented on src/components/Copyright/styled.js
> +export const ContainerText = ({ children }) =>
Removido.

2021-10-04 18:33 UTC, martinezpoa commented on src/components/Copyright/consts.js
> -  bgColor: 'neutral9',
Interessante, então dentro das consts de objeto ele entende que já default?

2021-10-05 02:07 UTC, gbombassaro commented on src/components/Copyright/consts.js
> -  bgColor: 'neutral9',
Sim! Pois fazemos o spread da constante nas props do componente.

Isso faz com que ele sempre assuma os valores que serão repassados no spread como default, a não ser que uma prop seja reescrita após o spread. Aí o valor da reescrita passa a ser o definido

2021-10-05 02:07 UTC, gbombassaro approved these changes

2021-10-05 02:10 UTC, merged