Cria componente MenuItem
xproglabs/prensa-designsystem pull request #84
Opened 2020-12-14 12:40 UTC by martinezpoa

2020-12-14 12:55 UTC, gbombassaro requested changes

2020-12-14 12:55 UTC, gbombassaro commented on components/MenuItem/index.js
> +import IcArrow from '../../icons/IcArrowForward'
Podes usar aqui o import relativo. Essa pasta tem um index.

```suggestion
import {IcArrow} from '../../icons'
```

2020-12-14 12:55 UTC, gbombassaro commented on components/MenuItem/index.js
> +const Container = styled.div`
Acho que não precisa desse Container. Pode usar somente o MenuItemContainer e passar esse margin-bottom pra ele.

2020-12-14 12:55 UTC, gbombassaro commented on components/MenuItem/index.js
> +  a {
Pode passar isso aqui para uma const? Que nem fez no MenuItemContainer. Ficaria algo tipo `const StyledAria = styled.a....`

No return, `<StyledAria>`

2020-12-14 12:55 UTC, gbombassaro commented on components/MenuItem/index.js
> +        <a>Economia</a>
Esse valor aqui deve ser dinâmico. Temos que adicionar duas props aqui, uma para cuidar do dado que corresponde ao título e outra para cuidar do href que o `<a>` vai receber.

2020-12-14 17:23 UTC, martinezpoa commented on components/MenuItem/index.js
> +import IcArrow from '../../icons/IcArrowForward'
Cara, o problema que tá dando é que se eu exporto só o icone, o componente não carrega no storybook, fica tudo branco, podemos revisar.

2020-12-30 11:56 UTC, gbombassaro requested changes

2020-12-30 11:56 UTC, gbombassaro commented on icons/IcArrowForward.js
> +      width={24}
Essa alteração aqui não faz sentido... Para alterar o tamanho deve ser feito no contexto em que está sendo usado e não no componente genérico

2020-12-30 11:56 UTC, gbombassaro commented on components/MenuItem/index.js
> +// Button.propTypes = {
PropTypes

2021-01-14 18:30 UTC, merged