[Feature] Amp/block with custom props
xproglabs/prensa-designsystem pull request #88
Opened 2020-12-26 01:16 UTC by bombassaro

Implemented feature amp/block with custom props to customize styles inline.

![screencapture-localhost-9009-iframe-html-2020-12-25-21_58_24](https://user-images.githubusercontent.com/1500027/103143926-ca9f3100-46fe-11eb-8d0c-d0b0d2ad294d.png)

2020-12-26 19:59 UTC, gbombassaro reviewed
Um comentário

2020-12-26 19:59 UTC, gbombassaro commented on components/AMP/Block/parser.js
> +    case 'demo':
Acho que aqui vai dar problema... O theme das props não passa uma string e sim um objeto com as propriedades disponíveis (valores de tokens). Derrepente mudar o nome da props e da function impeça de confundirmos com o theme que vem do Provider

2020-12-27 13:59 UTC, bombassaro commented on components/AMP/Block/parser.js
> +    case 'demo':
Renomeei para parseCustomDef, para a classe customizada pré-definida. Acredito que só vai ser usado para fins de exemplo e storybook

2020-12-27 14:00 UTC, bombassaro commented
Please can you check again @gbombassaro

2020-12-30 12:17 UTC, gbombassaro requested changes

2020-12-30 12:17 UTC, gbombassaro commented on styles/theme.js
> +  parseCustomDef,
Acho que o parseCustomDef não deveria estar aqui. Ele tem uma regra de negócio do Blocks dentro dele

2021-01-04 12:29 UTC, gbombassaro reviewed
Alguns comentários

2021-01-04 12:29 UTC, gbombassaro commented on styles/parsers/parseDimension.js
> +  let factor = 8;
Isso aqui pode vir do theme. Assim podemos definir diferentes fatores entre projetos

2021-01-04 12:29 UTC, gbombassaro commented on components/index.js
> +export {theme} from '../styles/theme'
Pq exportar o theme aqui? Acho que isso deve ser único em cada projeto... O do prensa seria o theme do storybook vamos dizer assim

2021-01-04 12:29 UTC, gbombassaro commented on styles/parsers/parseMargin.js
> +  let factor = 8;
Vamos passar esse aqui vindo do theme também

2021-01-04 12:29 UTC, gbombassaro commented on styles/parsers/parseMargin.js
> +  isNaN(mx) ?
Acho que podemos criar uma seção na documentação do blocks para explicar esse comportamento. Imagino uma seção separada, algo como um índice que explique regras de negócio do componente como essa troca de string | number

2021-01-04 12:33 UTC, bombassaro commented on components/index.js
> +export {theme} from '../styles/theme'
Poderia haver um theme default. No betbroker importei o theme com as vars default e reescrevi só o que precisei

2021-01-06 01:34 UTC, gbombassaro reviewed
Done

2021-01-06 01:37 UTC, merged